[package]
name = "vc-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
getrandom.workspace = true
base64.workspace = true
jsonwebtoken.workspace = true
vc-core.workspace = true
vc-auth.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
tokio.workspace = true
async-trait.workspace = true
reqwest.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
jsonschema = { version = "0.56", default-features = false }
