-- virtualCrypto baseline schema (Milestone 1).
--
-- Generated by scripts/generate-baseline.py from `pg_dump --schema-only`
-- of an empty database migrated with the Ecto migrations. Every statement
-- is idempotent so this applies cleanly both to a fresh database and to the
-- existing production database, where the objects already exist.
--
-- Do not edit by hand: regenerate instead.

DO $baseline$
BEGIN
CREATE TYPE public.openid_connect_application_type AS ENUM (
    'native',
    'web'
);
EXCEPTION WHEN duplicate_object THEN NULL;
END
$baseline$;;

DO $baseline$
BEGIN
CREATE TYPE public.openid_connect_grant_types AS ENUM (
    'unbound_authorization_code',
    'authorization_code',
    'refresh_token'
);
EXCEPTION WHEN duplicate_object THEN NULL;
END
$baseline$;;

DO $baseline$
BEGIN
CREATE TYPE public.openid_connect_response_types AS ENUM (
    'code'
);
EXCEPTION WHEN duplicate_object THEN NULL;
END
$baseline$;;

DO $baseline$
BEGIN
CREATE TYPE public.virtual_crypto_claim_status AS ENUM (
    'pending',
    'approved',
    'denied',
    'canceled'
);
EXCEPTION WHEN duplicate_object THEN NULL;
END
$baseline$;;

DO $baseline$
BEGIN
CREATE TYPE public.virtual_crypto_scope_type AS ENUM (
    'openid'
);
EXCEPTION WHEN duplicate_object THEN NULL;
END
$baseline$;;

CREATE OR REPLACE FUNCTION public.claim_metadata_remove_row() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  DELETE FROM claim_metadata WHERE id=NEW.id;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_metadata_strip_nulls() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
  BEGIN
    UPDATE claim_metadata SET metadata=jsonb_strip_nulls(NEW.metadata) WHERE id=NEW.id;
    RETURN NULL;
  END;
$$;

CREATE OR REPLACE FUNCTION public.delete_asset_by_id() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
  BEGIN
    DELETE FROM assets WHERE assets.id = NEW.id;
    RETURN NULL;
  END;
$$;

CREATE OR REPLACE FUNCTION public.metadata_limitation(json_obj jsonb) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
DECLARE
entry RECORD;
key_count INTEGER;
BEGIN
  key_count := 0;
  FOR entry IN (
    SELECT * FROM jsonb_each(json_obj)
  )
  LOOP
    key_count := key_count + 1;
    IF length(entry.key::text) > 40 OR jsonb_typeof(entry.value) != 'string' OR length(entry.value#>>'{}') > 500 OR key_count > 50 THEN
      RETURN FALSE;
    END IF;
  END LOOP;
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.metadata_limitation_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
  BEGIN
    RAISE check_violation;
  END;
$$;

CREATE TABLE IF NOT EXISTS public.access_tokens (
    id bigint NOT NULL,
    grant_id bigint,
    expires timestamp(0) without time zone,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    token_id uuid
);

CREATE SEQUENCE IF NOT EXISTS public.access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.access_tokens_id_seq OWNED BY public.access_tokens.id;

CREATE TABLE IF NOT EXISTS public.applications (
    id bigint NOT NULL,
    status integer,
    client_id uuid,
    client_secret character varying(255),
    response_types public.openid_connect_response_types[] DEFAULT ARRAY['code'::public.openid_connect_response_types],
    grant_types public.openid_connect_grant_types[] DEFAULT ARRAY['authorization_code'::public.openid_connect_grant_types],
    application_type public.openid_connect_application_type DEFAULT 'web'::public.openid_connect_application_type,
    client_name character varying(255),
    client_uri character varying(255),
    logo_uri character varying(255),
    owner_discord_id bigint,
    discord_support_server_invite_slug character varying(255),
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    webhook_url character varying(2048),
    public_key bytea NOT NULL,
    private_key bytea NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.applications_id_seq OWNED BY public.applications.id;

CREATE TABLE IF NOT EXISTS public.assets (
    id bigint NOT NULL,
    amount bigint,
    user_id bigint,
    currency_id bigint,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT amount_must_be_positive CHECK ((amount > 0))
);

CREATE SEQUENCE IF NOT EXISTS public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.assets_id_seq OWNED BY public.assets.id;

CREATE TABLE IF NOT EXISTS public.authorization_codes (
    id bigint NOT NULL,
    code character varying(255),
    redirect_uri character varying(255),
    application_id bigint,
    guild_id bigint,
    scopes public.virtual_crypto_scope_type[],
    expires timestamp(0) without time zone,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.authorization_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.authorization_codes_id_seq OWNED BY public.authorization_codes.id;

CREATE TABLE IF NOT EXISTS public.claim_metadata (
    id bigint NOT NULL,
    claim_id bigint NOT NULL,
    claimant_user_id bigint NOT NULL,
    payer_user_id bigint NOT NULL,
    owner_user_id bigint NOT NULL,
    metadata jsonb NOT NULL,
    CONSTRAINT metadata_must_be_object CHECK ((jsonb_typeof(metadata) = 'object'::text)),
    CONSTRAINT metadata_owner_is_must_related_user CHECK (((owner_user_id = claimant_user_id) OR (owner_user_id = payer_user_id)))
);

CREATE SEQUENCE IF NOT EXISTS public.claim_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.claim_metadata_id_seq OWNED BY public.claim_metadata.id;

CREATE TABLE IF NOT EXISTS public.claims (
    id bigint NOT NULL,
    amount bigint,
    status public.virtual_crypto_claim_status,
    claimant_user_id bigint NOT NULL,
    payer_user_id bigint NOT NULL,
    currency_id bigint NOT NULL,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.claims_id_seq OWNED BY public.claims.id;

CREATE TABLE IF NOT EXISTS public.currencies (
    id bigint NOT NULL,
    name character varying(255),
    unit character varying(255),
    guild_id bigint,
    pool_amount bigint,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT pool_amount_must_not_be_negative CHECK ((pool_amount >= 0))
);

CREATE TABLE IF NOT EXISTS public.currency_given_histories (
    id bigint NOT NULL,
    amount bigint,
    receiver_id bigint,
    currency_id bigint,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    "time" timestamp(0) without time zone
);

CREATE TABLE IF NOT EXISTS public.currency_payment_histories (
    id bigint NOT NULL,
    amount bigint,
    sender_id bigint,
    receiver_id bigint,
    currency_id bigint,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    "time" timestamp(0) without time zone
);

CREATE TABLE IF NOT EXISTS public.discord_users (
    id bigint NOT NULL,
    discord_user_id bigint,
    refresh_token character varying(255),
    token character varying(255),
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    expires timestamp(0) without time zone
);

CREATE SEQUENCE IF NOT EXISTS public.discord_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.discord_users_id_seq OWNED BY public.discord_users.id;

CREATE TABLE IF NOT EXISTS public.grant_scopes (
    id bigint NOT NULL,
    grant_id bigint,
    scope public.virtual_crypto_scope_type,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.grant_scopes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.grant_scopes_id_seq OWNED BY public.grant_scopes.id;

CREATE TABLE IF NOT EXISTS public.grants (
    id bigint NOT NULL,
    application_id bigint,
    guild_id bigint,
    latest_code character varying(255),
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.grants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.grants_id_seq OWNED BY public.grants.id;

CREATE SEQUENCE IF NOT EXISTS public.info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.info_id_seq OWNED BY public.currencies.id;

CREATE SEQUENCE IF NOT EXISTS public.money_given_historys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.money_given_historys_id_seq OWNED BY public.currency_given_histories.id;

CREATE SEQUENCE IF NOT EXISTS public.money_payment_historys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.money_payment_historys_id_seq OWNED BY public.currency_payment_histories.id;

CREATE TABLE IF NOT EXISTS public.payments_idempotency (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    idempotency_key bytea NOT NULL,
    expires timestamp(0) without time zone NOT NULL,
    http_status integer,
    body jsonb,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.payments_idempotency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.payments_idempotency_id_seq OWNED BY public.payments_idempotency.id;

CREATE TABLE IF NOT EXISTS public.redirect_uris (
    id bigint NOT NULL,
    application_id bigint,
    redirect_uri character varying(255),
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.redirect_uris_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.redirect_uris_id_seq OWNED BY public.redirect_uris.id;

CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id bigint NOT NULL,
    grant_id bigint,
    expires timestamp(0) without time zone,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    token_id uuid
);

CREATE SEQUENCE IF NOT EXISTS public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version bigint NOT NULL,
    inserted_at timestamp(0) without time zone
);

CREATE TABLE IF NOT EXISTS public.user_access_tokens (
    id bigint NOT NULL,
    user_id bigint,
    token_id uuid,
    expires timestamp(0) without time zone,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS public.user_access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.user_access_tokens_id_seq OWNED BY public.user_access_tokens.id;

CREATE TABLE IF NOT EXISTS public.users (
    id integer NOT NULL,
    status integer,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    discord_id bigint,
    application_id bigint
);

CREATE SEQUENCE IF NOT EXISTS public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

ALTER TABLE ONLY public.access_tokens ALTER COLUMN id SET DEFAULT nextval('public.access_tokens_id_seq'::regclass);

ALTER TABLE ONLY public.applications ALTER COLUMN id SET DEFAULT nextval('public.applications_id_seq'::regclass);

ALTER TABLE ONLY public.assets ALTER COLUMN id SET DEFAULT nextval('public.assets_id_seq'::regclass);

ALTER TABLE ONLY public.authorization_codes ALTER COLUMN id SET DEFAULT nextval('public.authorization_codes_id_seq'::regclass);

ALTER TABLE ONLY public.claim_metadata ALTER COLUMN id SET DEFAULT nextval('public.claim_metadata_id_seq'::regclass);

ALTER TABLE ONLY public.claims ALTER COLUMN id SET DEFAULT nextval('public.claims_id_seq'::regclass);

ALTER TABLE ONLY public.currencies ALTER COLUMN id SET DEFAULT nextval('public.info_id_seq'::regclass);

ALTER TABLE ONLY public.currency_given_histories ALTER COLUMN id SET DEFAULT nextval('public.money_given_historys_id_seq'::regclass);

ALTER TABLE ONLY public.currency_payment_histories ALTER COLUMN id SET DEFAULT nextval('public.money_payment_historys_id_seq'::regclass);

ALTER TABLE ONLY public.discord_users ALTER COLUMN id SET DEFAULT nextval('public.discord_users_id_seq'::regclass);

ALTER TABLE ONLY public.grant_scopes ALTER COLUMN id SET DEFAULT nextval('public.grant_scopes_id_seq'::regclass);

ALTER TABLE ONLY public.grants ALTER COLUMN id SET DEFAULT nextval('public.grants_id_seq'::regclass);

ALTER TABLE ONLY public.payments_idempotency ALTER COLUMN id SET DEFAULT nextval('public.payments_idempotency_id_seq'::regclass);

ALTER TABLE ONLY public.redirect_uris ALTER COLUMN id SET DEFAULT nextval('public.redirect_uris_id_seq'::regclass);

ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.refresh_tokens_id_seq'::regclass);

ALTER TABLE ONLY public.user_access_tokens ALTER COLUMN id SET DEFAULT nextval('public.user_access_tokens_id_seq'::regclass);

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'access_tokens_pkey'
      AND conrelid = 'public.access_tokens'::regclass) THEN
    ALTER TABLE ONLY public.access_tokens
    ADD CONSTRAINT access_tokens_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'applications_pkey'
      AND conrelid = 'public.applications'::regclass) THEN
    ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assets_pkey'
      AND conrelid = 'public.assets'::regclass) THEN
    ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'authorization_codes_pkey'
      AND conrelid = 'public.authorization_codes'::regclass) THEN
    ALTER TABLE ONLY public.authorization_codes
    ADD CONSTRAINT authorization_codes_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claim_metadata_pkey'
      AND conrelid = 'public.claim_metadata'::regclass) THEN
    ALTER TABLE ONLY public.claim_metadata
    ADD CONSTRAINT claim_metadata_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_pkey'
      AND conrelid = 'public.claims'::regclass) THEN
    ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_unique_ordered_claim_metadata_fk'
      AND conrelid = 'public.claims'::regclass) THEN
    ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_unique_ordered_claim_metadata_fk UNIQUE (id, claimant_user_id, payer_user_id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'discord_users_pkey'
      AND conrelid = 'public.discord_users'::regclass) THEN
    ALTER TABLE ONLY public.discord_users
    ADD CONSTRAINT discord_users_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'grant_scopes_pkey'
      AND conrelid = 'public.grant_scopes'::regclass) THEN
    ALTER TABLE ONLY public.grant_scopes
    ADD CONSTRAINT grant_scopes_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'grants_pkey'
      AND conrelid = 'public.grants'::regclass) THEN
    ALTER TABLE ONLY public.grants
    ADD CONSTRAINT grants_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'info_pkey'
      AND conrelid = 'public.currencies'::regclass) THEN
    ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT info_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_given_historys_pkey'
      AND conrelid = 'public.currency_given_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_given_histories
    ADD CONSTRAINT money_given_historys_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_payment_historys_pkey'
      AND conrelid = 'public.currency_payment_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_payment_histories
    ADD CONSTRAINT money_payment_historys_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_idempotency_pkey'
      AND conrelid = 'public.payments_idempotency'::regclass) THEN
    ALTER TABLE ONLY public.payments_idempotency
    ADD CONSTRAINT payments_idempotency_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'redirect_uris_pkey'
      AND conrelid = 'public.redirect_uris'::regclass) THEN
    ALTER TABLE ONLY public.redirect_uris
    ADD CONSTRAINT redirect_uris_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'refresh_tokens_pkey'
      AND conrelid = 'public.refresh_tokens'::regclass) THEN
    ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'schema_migrations_pkey'
      AND conrelid = 'public.schema_migrations'::regclass) THEN
    ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_access_tokens_pkey'
      AND conrelid = 'public.user_access_tokens'::regclass) THEN
    ALTER TABLE ONLY public.user_access_tokens
    ADD CONSTRAINT user_access_tokens_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_pkey'
      AND conrelid = 'public.users'::regclass) THEN
    ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
  END IF;
END
$baseline$;;

CREATE INDEX IF NOT EXISTS access_tokens_expires_index ON public.access_tokens USING btree (expires);

CREATE UNIQUE INDEX IF NOT EXISTS access_tokens_id_index ON public.access_tokens USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS access_tokens_token_id_index ON public.access_tokens USING btree (token_id);

CREATE UNIQUE INDEX IF NOT EXISTS applications_client_id_index ON public.applications USING btree (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS applications_id_index ON public.applications USING btree (id);

CREATE INDEX IF NOT EXISTS applications_owner_discord_id_index ON public.applications USING btree (owner_discord_id);

CREATE INDEX IF NOT EXISTS assets_money_id_index ON public.assets USING btree (currency_id);

CREATE INDEX IF NOT EXISTS assets_user_id_index ON public.assets USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS assets_user_id_money_id_index ON public.assets USING btree (user_id, currency_id);

CREATE UNIQUE INDEX IF NOT EXISTS authorization_codes_code_index ON public.authorization_codes USING btree (code);

CREATE INDEX IF NOT EXISTS authorization_codes_expires_index ON public.authorization_codes USING btree (expires);

CREATE UNIQUE INDEX IF NOT EXISTS authorization_codes_id_index ON public.authorization_codes USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS claim_metadata_claim_id_owner_user_id_index ON public.claim_metadata USING btree (claim_id, owner_user_id);

CREATE INDEX IF NOT EXISTS claims_claimant_user_id_index ON public.claims USING btree (claimant_user_id);

CREATE INDEX IF NOT EXISTS claims_payer_user_id_index ON public.claims USING btree (payer_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS discord_users_discord_user_id_index ON public.discord_users USING btree (discord_user_id);

CREATE INDEX IF NOT EXISTS discord_users_refresh_token_index ON public.discord_users USING btree (refresh_token);

CREATE INDEX IF NOT EXISTS discord_users_token_index ON public.discord_users USING btree (token);

CREATE UNIQUE INDEX IF NOT EXISTS grant_scopes_grant_id_scope_index ON public.grant_scopes USING btree (grant_id, scope);

CREATE UNIQUE INDEX IF NOT EXISTS grant_scopes_id_index ON public.grant_scopes USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS grants_application_id_guild_id_index ON public.grants USING btree (application_id, guild_id);

CREATE UNIQUE INDEX IF NOT EXISTS grants_id_index ON public.grants USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS grants_latest_code_index ON public.grants USING btree (latest_code);

CREATE UNIQUE INDEX IF NOT EXISTS info_guild_id_index ON public.currencies USING btree (guild_id);

CREATE UNIQUE INDEX IF NOT EXISTS info_name_index ON public.currencies USING btree (name);

CREATE UNIQUE INDEX IF NOT EXISTS info_unit_index ON public.currencies USING btree (unit);

CREATE INDEX IF NOT EXISTS money_given_historys_money_id_index ON public.currency_given_histories USING btree (currency_id);

CREATE INDEX IF NOT EXISTS money_given_historys_receiver_id_index ON public.currency_given_histories USING btree (receiver_id);

CREATE INDEX IF NOT EXISTS money_payment_historys_money_id_index ON public.currency_payment_histories USING btree (currency_id);

CREATE INDEX IF NOT EXISTS money_payment_historys_receiver_id_index ON public.currency_payment_histories USING btree (receiver_id);

CREATE INDEX IF NOT EXISTS money_payment_historys_sender_id_index ON public.currency_payment_histories USING btree (sender_id);

CREATE UNIQUE INDEX IF NOT EXISTS payments_idempotency_id_index ON public.payments_idempotency USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS payments_idempotency_idempotency_key_user_id_index ON public.payments_idempotency USING btree (idempotency_key, user_id);

CREATE UNIQUE INDEX IF NOT EXISTS redirect_uris_application_id_redirect_uri_index ON public.redirect_uris USING btree (application_id, redirect_uri);

CREATE INDEX IF NOT EXISTS refresh_tokens_expires_index ON public.refresh_tokens USING btree (expires);

CREATE UNIQUE INDEX IF NOT EXISTS refresh_tokens_grant_id_index ON public.refresh_tokens USING btree (grant_id);

CREATE UNIQUE INDEX IF NOT EXISTS refresh_tokens_id_index ON public.refresh_tokens USING btree (id);

CREATE UNIQUE INDEX IF NOT EXISTS refresh_tokens_token_id_index ON public.refresh_tokens USING btree (token_id);

CREATE UNIQUE INDEX IF NOT EXISTS text_claims_id ON public.claims USING btree (((id)::text));

CREATE INDEX IF NOT EXISTS user_access_tokens_expires_index ON public.user_access_tokens USING btree (expires);

CREATE UNIQUE INDEX IF NOT EXISTS user_access_tokens_token_id_index ON public.user_access_tokens USING btree (token_id);

CREATE INDEX IF NOT EXISTS user_access_tokens_user_id_index ON public.user_access_tokens USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS users_application_id_index ON public.users USING btree (application_id);

CREATE UNIQUE INDEX IF NOT EXISTS users_discord_id_index ON public.users USING btree (discord_id);

CREATE UNIQUE INDEX IF NOT EXISTS users_id_index ON public.users USING btree (id);

DROP TRIGGER IF EXISTS _remove_entry_if_empty ON public.claim_metadata;
CREATE TRIGGER _remove_entry_if_empty BEFORE UPDATE OF metadata ON public.claim_metadata FOR EACH ROW WHEN (('{}'::jsonb @> new.metadata)) EXECUTE FUNCTION public.claim_metadata_remove_row();

DROP TRIGGER IF EXISTS delete_asset_when_amount_is_zero ON public.assets;
CREATE TRIGGER delete_asset_when_amount_is_zero BEFORE INSERT OR UPDATE OF amount ON public.assets FOR EACH ROW WHEN ((new.amount = 0)) EXECUTE FUNCTION public.delete_asset_by_id();

DROP TRIGGER IF EXISTS metadata_limitation ON public.claim_metadata;
CREATE TRIGGER metadata_limitation BEFORE UPDATE OF metadata ON public.claim_metadata FOR EACH ROW WHEN ((NOT public.metadata_limitation(new.metadata))) EXECUTE FUNCTION public.metadata_limitation_trigger();

DROP TRIGGER IF EXISTS strip_nulls_after_insert ON public.claim_metadata;
CREATE TRIGGER strip_nulls_after_insert AFTER INSERT ON public.claim_metadata FOR EACH ROW EXECUTE FUNCTION public.claim_metadata_strip_nulls();

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'access_tokens_grant_id_fkey'
      AND conrelid = 'public.access_tokens'::regclass) THEN
    ALTER TABLE ONLY public.access_tokens
    ADD CONSTRAINT access_tokens_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES public.grants(id) ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assets_money_id_fkey'
      AND conrelid = 'public.assets'::regclass) THEN
    ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_money_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currencies(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assets_user_id_fkey'
      AND conrelid = 'public.assets'::regclass) THEN
    ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'authorization_codes_application_id_fkey'
      AND conrelid = 'public.authorization_codes'::regclass) THEN
    ALTER TABLE ONLY public.authorization_codes
    ADD CONSTRAINT authorization_codes_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claim_metadata_claim_id_fkey'
      AND conrelid = 'public.claim_metadata'::regclass) THEN
    ALTER TABLE ONLY public.claim_metadata
    ADD CONSTRAINT claim_metadata_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claim_metadata_claimant_user_id_fkey'
      AND conrelid = 'public.claim_metadata'::regclass) THEN
    ALTER TABLE ONLY public.claim_metadata
    ADD CONSTRAINT claim_metadata_claimant_user_id_fkey FOREIGN KEY (claimant_user_id) REFERENCES public.users(id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claim_metadata_fk'
      AND conrelid = 'public.claim_metadata'::regclass) THEN
    ALTER TABLE ONLY public.claim_metadata
    ADD CONSTRAINT claim_metadata_fk FOREIGN KEY (claim_id, claimant_user_id, payer_user_id) REFERENCES public.claims(id, claimant_user_id, payer_user_id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claim_metadata_owner_user_id_fkey'
      AND conrelid = 'public.claim_metadata'::regclass) THEN
    ALTER TABLE ONLY public.claim_metadata
    ADD CONSTRAINT claim_metadata_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claim_metadata_payer_user_id_fkey'
      AND conrelid = 'public.claim_metadata'::regclass) THEN
    ALTER TABLE ONLY public.claim_metadata
    ADD CONSTRAINT claim_metadata_payer_user_id_fkey FOREIGN KEY (payer_user_id) REFERENCES public.users(id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_claimant_user_id_fkey'
      AND conrelid = 'public.claims'::regclass) THEN
    ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_claimant_user_id_fkey FOREIGN KEY (claimant_user_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_money_info_id_fkey'
      AND conrelid = 'public.claims'::regclass) THEN
    ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_money_info_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currencies(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claims_payer_user_id_fkey'
      AND conrelid = 'public.claims'::regclass) THEN
    ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_payer_user_id_fkey FOREIGN KEY (payer_user_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'discord_users_discord_user_id_fkey'
      AND conrelid = 'public.discord_users'::regclass) THEN
    ALTER TABLE ONLY public.discord_users
    ADD CONSTRAINT discord_users_discord_user_id_fkey FOREIGN KEY (discord_user_id) REFERENCES public.users(discord_id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'grant_scopes_grant_id_fkey'
      AND conrelid = 'public.grant_scopes'::regclass) THEN
    ALTER TABLE ONLY public.grant_scopes
    ADD CONSTRAINT grant_scopes_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES public.grants(id) ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'grants_application_id_fkey'
      AND conrelid = 'public.grants'::regclass) THEN
    ALTER TABLE ONLY public.grants
    ADD CONSTRAINT grants_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_given_historys_money_id_fkey'
      AND conrelid = 'public.currency_given_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_given_histories
    ADD CONSTRAINT money_given_historys_money_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currencies(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_given_historys_receiver_id_fkey'
      AND conrelid = 'public.currency_given_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_given_histories
    ADD CONSTRAINT money_given_historys_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_payment_historys_money_id_fkey'
      AND conrelid = 'public.currency_payment_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_payment_histories
    ADD CONSTRAINT money_payment_historys_money_id_fkey FOREIGN KEY (currency_id) REFERENCES public.currencies(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_payment_historys_receiver_id_fkey'
      AND conrelid = 'public.currency_payment_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_payment_histories
    ADD CONSTRAINT money_payment_historys_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'money_payment_historys_sender_id_fkey'
      AND conrelid = 'public.currency_payment_histories'::regclass) THEN
    ALTER TABLE ONLY public.currency_payment_histories
    ADD CONSTRAINT money_payment_historys_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_idempotency_user_id_fkey'
      AND conrelid = 'public.payments_idempotency'::regclass) THEN
    ALTER TABLE ONLY public.payments_idempotency
    ADD CONSTRAINT payments_idempotency_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'redirect_uris_application_id_fkey'
      AND conrelid = 'public.redirect_uris'::regclass) THEN
    ALTER TABLE ONLY public.redirect_uris
    ADD CONSTRAINT redirect_uris_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'refresh_tokens_grant_id_fkey'
      AND conrelid = 'public.refresh_tokens'::regclass) THEN
    ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES public.grants(id) ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_access_tokens_user_id_fkey'
      AND conrelid = 'public.user_access_tokens'::regclass) THEN
    ALTER TABLE ONLY public.user_access_tokens
    ADD CONSTRAINT user_access_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
  END IF;
END
$baseline$;;

DO $baseline$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_application_id_fkey'
      AND conrelid = 'public.users'::regclass) THEN
    ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id);
  END IF;
END
$baseline$;;
