-- A nonempty resource set is an explicit restriction; an empty set grants access
-- to every currency. Cascading deletion of the last currency would therefore
-- widen an existing grant. Keep the approved ids even after their currencies
-- disappear. Currency ids are generated by a sequence and are not reused by
-- currency creation, so these retained ids cannot authorize a replacement.
-- The grant foreign key still removes the rows when the grant itself is deleted.
ALTER TABLE public.grant_resources
    DROP CONSTRAINT IF EXISTS grant_resources_currency_id_fkey;
