[package]
name = "vc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
getrandom.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
uuid.workspace = true
thiserror.workspace = true
tracing.workspace = true
