[package]
name = "vc-demo-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true

[[bin]]
name = "demo-issue"
path = "src/bin/demo-issue.rs"
